config glue for recvmsg(2) and CMSG_FIRSTHDR(3); needed for Solaris 11

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -44,12 +44,15 @@ LDADD=
 LDFLAGS=
 LD_NANOSLEEP=
 LD_OHASH=
+LD_RECVMSG=
 STATIC="-static"
 
 BUILD_CGI=0
 BUILD_CATMAN=0
 INSTALL_LIBMANDOC=0
 
+HAVE_CMSG=
+HAVE_CMSG_XPG42=0
 HAVE_DIRENT_NAMLEN=
 HAVE_EFTYPE=
 HAVE_ENDIAN=
@@ -67,6 +70,7 @@ HAVE_PATH_MAX=
 HAVE_PLEDGE=
 HAVE_PROGNAME=
 HAVE_REALLOCARRAY=
+HAVE_RECVMSG=
 HAVE_REWB_BSD=
 HAVE_REWB_SYSV=
 HAVE_SANDBOX_INIT=
@@ -267,6 +271,36 @@ if [ "${HAVE_NANOSLEEP}" -eq 0 ]; then
 	exit 1
 fi
 
+if [ ${BUILD_CATMAN} -gt 0 ]; then
+	# --- recvmsg ---
+	if [ -n "${LD_RECVMSG}" ]; then
+		runtest recvmsg RECVMSG "${LD_RECVMSG}" || true
+	elif singletest recvmsg RECVMSG; then
+		:
+	elif runtest recvmsg RECVMSG "-lsocket"; then
+		LD_RECVMSG="-lsocket"
+	fi
+	if [ "${HAVE_RECVMSG}" -eq 0 ]; then
+		echo "FATAL: recvmsg: no" 1>&2
+		echo "FATAL: recvmsg: no" 1>&3
+		echo "Without recvmsg(2), you cannot BUILD_CATMAN." 1>&2
+		exit 1
+	fi
+
+	# --- cmsg ---
+	if singletest cmsg CMSG; then
+		:
+	elif runtest cmsg CMSG "-D_XPG4_2"; then
+		HAVE_CMSG_XPG42=1
+	fi
+	if [ "${HAVE_CMSG}" -eq 0 ]; then
+		echo "FATAL: cmsg: no" 1>&2
+		echo "FATAL: cmsg: no" 1>&3
+		echo "Without CMSG_FIRSTHDR(3), you cannot BUILD_CATMAN." 1>&2
+		exit 1
+	fi
+fi
+
 # --- ohash ---
 if ismanual ohash OHASH "${HAVE_OHASH}"; then
 	:
@@ -282,7 +316,7 @@ if [ "${HAVE_OHASH}" -eq 0 ]; then
 fi
 
 # --- LDADD ---
-LDADD="${LDADD} ${LD_NANOSLEEP} ${LD_OHASH} -lz"
+LDADD="${LDADD} ${LD_NANOSLEEP} ${LD_RECVMSG} ${LD_OHASH} -lz"
 echo "LDADD=\"${LDADD}\"" 1>&2
 echo "LDADD=\"${LDADD}\"" 1>&3
 echo 1>&3
@@ -326,6 +360,7 @@ if [ ${HAVE_ENDIAN} -eq 0 -a ${HAVE_SYS_ENDIAN} -eq 0 ]; then
 fi
 
 cat << __HEREDOC__
+#define HAVE_CMSG_XPG42 ${HAVE_CMSG_XPG42}
 #define HAVE_DIRENT_NAMLEN ${HAVE_DIRENT_NAMLEN}
 #define HAVE_ENDIAN ${HAVE_ENDIAN}
 #define HAVE_ERR ${HAVE_ERR}
